name: dockerized-nestjs-api

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and test
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test

      - name: build code
        run: npm run build
