name: dockerized-nestjs-api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: change to api dir
        run: cd dockerized-nestjs-api/api

      - name: install dependencies
        run: npm install

      - name: build and test
        run: npm run build && npm run test
